theme: minima
title: Welcome to Minnieshay's homepage!
author: Minnieshay
email: srankinbusiness@gmail.cocm
description: > # this means to ignore newlines until "baseurl:"
  Feel free to bookmark this to keep an eye on my project updates.

# social links
twitter_username: ShaquantaR # DO NOT include the @ character, or else the build will fail!
github_username:  Minnieshay # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
